language: java
jdk:
  - openjdk11
before_install:
  - chmod -R 777 mvnw
before_deploy:
  - sudo apt-get install sshpass  # 安装sshpass
script:
  - ./mvnw clean install
deploy:
  - provider: script
    script: ./scripts/deploy.sh $SERVER $PASSWORD
    skip_cleanup: true
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify