language: java
jdk:
  - openjdk11
before_install:
  - chmod -R 777 mvnw
#  - sudo apt-get install sshpass
script:
  - ./mvnw clean install
#deploy:
#  - provider: script
#    script: bash ./scripts/deploy.sh $SERVER $PASSWORD
#    skip_cleanup: true
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify