language: java
jdk:
  - openjdk11
before_install:
  - chmod -R 777 mvnw
  - sudo apt-get install sshpass
script:
  - ./mvnw clean install
  - sshpass -p $PASSWORD scp violet-app/violet-app-admin/target/violet-app-admin-0.0.1-SNAPSHOT.jar root@$SERVER:/root/violet/app/admin
deploy:
  - provider: script
    script: ./scripts/deploy.sh $SERVER $PASSWORD
    skip_cleanup: true
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify