# This is a basic workflow to help you get started with Actions
name: Build and push docker images

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./violet-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: guqing/violet-gateway:latest
      -
        name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./violet-auth/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: guqing/violet-auth:latest 
      -
        name: Build and push app admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./violet-app/violet-app-admin/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: guqing/violet-app-admin:latest  


