# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Violet Cloud CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dnacos.url=${{ secrets.NACOS_URL }}
      env:
        nacos.url: ${{ secrets.NACOS_URL }}
#    - name: Before Deploy
#      run: chmod -R 777 mvnw & sudo apt-get install sshpass
#    - name: Deploy
#      env:
#       SERVER: ${{ secrets.SERVER_IP }}
#       PASSWORD: ${{ secrets.PASSWORD }}
#      run: bash ./scripts/deploy.sh $SERVER $PASSWORD

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: ./violet-gateway/
          file: ./violet-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: guqing/violet-gateway:latest
      -
        name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: ./violet-auth/
          file: ./violet-auth/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: guqing/violet-auth:latest
      -
        name: Build and push app admin
        uses: docker/build-push-action@v2
        with:
          context: ./violet-app/violet-app-admin/
          file: ./violet-app/violet-app-admin/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: guqing/violet-app-admin:latest
