# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Violet Cloud CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dnacos.url=${{ secrets.NACOS_URL }}
      env:
        nacos.url: ${{ secrets.NACOS_URL }}
#    - name: Before Deploy
#      run: chmod -R 777 mvnw & sudo apt-get install sshpass
#    - name: Deploy
#      env:
#       SERVER: ${{ secrets.SERVER_IP }}
#       PASSWORD: ${{ secrets.PASSWORD }}
#      run: bash ./scripts/deploy.sh $SERVER $PASSWORD

    -
      name: Build And Push Docker Image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: bash ./scripts/docker-build.sh $DOCKERHUB_USERNAME $DOCKERHUB_TOKEN latest
